### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TechAle** [TechAle/gamesense-website#1]
- [X] Make logo in css
- [X] Create a lot of sketch 
- [X] Ask to hossier which does he like the most and wait his response
- [x] Create main page
 - [ ] Create showcase
 - [ ] Create Download page
 - [ ] Create Developer page
 - [ ] Create FAQ page
 - [ ] Create config page
